// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/contact";
  };
  "./layout/layout.tsx": {
    id: "layout/layout";
    page: "/" | "/about" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./views/about/about.tsx": {
    id: "views/about/about";
    page: "/about";
  };
  "./views/contact/contact.tsx": {
    id: "views/contact/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layout/layout": typeof import("./app/./layout/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "views/about/about": typeof import("./app/./views/about/about.tsx");
  "views/contact/contact": typeof import("./app/./views/contact/contact.tsx");
};